### PR TITLE
Infix operators

### PR DESCRIPTION
**Pull request by Lokeh**
Implements `>>=` and `=<<`.

We could think about adding `flatMap` and `>>|` / `|<<` as well.

### CODE REVIEW

**Comment by wokalski** [comment]
This PR looks great 🎉.

I think that `=<<` is not necessary. It's even discouraged by the Lwt docs.

When it comes to flatMap, what would it be its implementation/functionality?

Also, what do you think about current naming? I admit that it's not very idiomatic but I was trying to make it friendly for everyone.

**Comment by Lokeh** [comment]
I'd be fine with removing `=<<`, I put it in more to be complete than for my own uses :P.

I was ready to add infix to `Vow.t`, but I was worried that it would get confusing/cumbersome if one wanted to open both (e.g. you were using both `Vow.t` and `Vow.Result.t`). If I understand how to use the library correctly, it seems like we should be encouraging consumers to use `Vow.Result.t` anyway so I added the Infix module just to that. Obviously you have a better understanding of how to use the library, so if you think it's worthwhile then 👍 

Naming and whatnot is tricky. Actually, thinking about it more, the current `map` would commonly be referred to as `flatMap` or `bind`; map is typically `('a => 'b) => t 'a => t 'b`, whereas bind/flatMap is `('a => t 'b) => t 'a => t 'b`. I think keeping the API map/flatMap/return/onError/etc. is nice because it matches naming and APIs that JS developers are relatively familiar with.

I think the importance on friendliness over "correctness" is important, which is why I think that having both `map`/`flatMap` is good; usually I just want to `map` from `'a => 'b` without worrying about promises. The more I can hide async and keep it out of my code, the better.

I currently have a PR I'm developing over at https://github.com/Lokeh/bucklescript/blob/master/jscomp/others/js_promise.ml#L54 for a very "monadic" implementation of a promise API a la Lwt, but I see Vow as potentially the more friendlier and ergonomic version of that since you get better support from the type system (at the cost of boxing/unboxing).

**Comment by wokalski** [comment]
The cost of boxing/unboxing doesn't get you better support from the type system. It's just because `Js.Promise`s  are not monadic. Js Promises unwrap when they are nested.

The support from the type system could be the same regardless.

I'm okay with not adding `Infix` for `Vow`. I almost don't use `Vow.t`.

It'd be also cool if you add flatMap.

**Comment by wokalski** [comment]
@Lokeh any update here? I can merge if anything because it's pretty cool regardless.

**Comment by Lokeh** [comment]
Do you think there should be a `map` function for both `handled` and `unhandled`? As in, should there be functions for both `('a => 'b) => t 'a 'error handled` and `('a => 'b) => t 'a unhandled`, or just handled?

**Comment by wokalski** [comment]
`mapUnhandled` exists so that you can handle several errors with one error handler. It's a common pattern with promises. Like `then().then().then().catch()`.

**Comment by Lokeh** [comment]
Sorry, I probably wasn't clear.

Right now, vow's `map` function is `('a => t 'b) => t 'a => t 'b`. This is *usually* called `flatMap` or `bind`, and `map` is usually `('a => 'b) => t 'a => t 'b`.

I'm proposing that we provide a `flatMap`, `flatMapUnhandled` and `>>=` functions that are the same as the current `map` functions, and then provide a new `map`/`mapUnhandled` that have the second form above.

I think that this is unrelated to this current PR, though, so I'll create a new PR with those changes and we can talk about it there.

**Comment by wokalski** [comment]
ok, so tldr; I'm merging this one, right?

**Comment by Lokeh** [comment]
Just resolved the conflicts, so should be good-to-go 👍  yep.

**Comment by wokalski** [comment]
Thank you!

**Pull request merged**
